config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :chefs, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookings, only: [ :create, :new ]
  end
  resources :bookings, only: [:destroy]
  resource :dashboard, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :chef
  validates :start_time, presence: true
  validates :end_time, presence: true

  def calculate_total_price
    (end_time - start_time).to_i * chef.price
  end
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :chefs, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @chef = Chef.find(params[:chef_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @chef = Chef.find(params[:chef_id])
    @booking.chef = @chef
    @booking.user = current_user
    @booking.total_price = @booking.calculate_total_price

    if @booking.save
      redirect_to dashboard_path(), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to chef_path(@booking.list)
  end


  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :total_price)
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
    @chefs = Chef.all
    @markers = @chefs.geocoded.map do |chef|
      {
        lat: chef.latitude,
        lng: chef.longitude
      }
    end
  end

  def show
    @chef = Chef.find(params[:id])
    @booking = Booking.new
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    @chef.user = current_user


    if @chef.save
      redirect_to chef_path(@chef)
    else
      render :new
    end
  end

  private

  def chef_params
    params.require(:chef).permit(:first_name, :last_name, :location, :rating, :speciality, :price, :description)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @chefs = current_user.chefs
    @bookings = current_user.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for [@chef, @booking] do |f| %>
     <%= f.input :start_time %>
      <%= f.input :end_time %>

    <%= f.submit %>
<% end %>

app/views/chefs/index.html.erb
<h2 class="chef-list">CHEF'S LIST</h2>
<p class="chef-list"> Choose a chef to view more details for booking</p>
<br>

      <div class="container-map">
        <div id="map"
          style="width: 100%; height: 250px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          <%= link_to 'New Chef', new_chef_path, class: 'btn chef-btn chef js-scroll-trigger'%>
          <%= link_to 'Back', root_path, class: 'btn chef-btn js-scroll-trigger' %>
        </div>
      </div>
</div>

<section class="wrapper">
  <div class="container">

<div class="row"><% @chefs.each do |chef| %>
 <div class="col-sm-4"><div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1551218808-94e220e084d2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80');">
         <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
         <div class="card-body">

              <h2><%= chef.first_name %> <%= chef.last_name %></h2> <br>
              <h6>Rating: <%= chef.rating %></h6><br>
              <h6>Speciality: <%= chef.speciality %></h6><br>
              <h6>Price per day: <%= chef.price %>TL</h6><br>
              <h6>Description: <%= chef.description %></h6><br>
              <%= link_to 'View', chef_path(chef), class: 'btn btn-view js-scroll-trigger'%>

          </div>
          <div class="card-footer">
           <div class="media">
              <div class="media-body">
              <h6 class="my-0 text-white d-block"></h6>
              </div>
</div>
          </div>
        </div>
      </div></div><% end %>


</div>

</div>
</section>

app/views/chefs/new.html.erb
<div class="container mt-4">
  <h2 class="mb-4">Create a New Chef</h2>
  <%= simple_form_for(@chef) do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :rating %>
      <%= f.input :location %>
      <%= f.input :description %>
      <%= f.input :speciality %>
      <%= f.input :price %>
      <%= f.submit class: "btn" %>
    <% end %>
    <%= link_to 'BACK', chefs_path, class: 'btn' %>
</div>

app/views/chefs/show.html.erb
<section class="light">
	<div class="container py-2">
		<div class="h1 text-center text-dark" id="pageHeaderTitle"></div>

		<article class="postcard light red">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://images.unsplash.com/photo-1572715376701-98568319fd0b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80" alt="Image Title" />
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title blue"><a href="#"><%= @chef.first_name %> <%= @chef.last_name %></a></h1>
				<div class="postcard__subtitle small">
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"><%= @chef.description %> |  |  <%= @chef.speciality %> |  | <%= @chef.location %>
          <%= simple_form_for [@chef, @booking] do |f| %>
            <%= f.input :start_time %>
            <%= f.input :end_time %>

            <%= f.submit class: "btn" %>
            <%= link_to 'Back', chefs_path, class: 'btn' %>
          <% end %>
        </div>
				<ul class="postcard__tagbox">
					<li class="tag__item"><i class="fas fa-tag mr-2"></i>Price: <%= @chef.price %> TL</li>
					<li class="tag__item"><i class="fas fa-clock mr-2"></i>Rating: <%= @chef.rating %></li>
					<li class="tag__item play blue">
						<a href="#"><i class="fas fa-play mr-2"></i>View</a>
					</li>
				</ul>
			</div>
</section>

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Chefs</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Bookings</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <div class="index-header">
      <h2>My Chefs</h2>
    </div>

    <section class="wrapper">
    <% @chefs.each do |chef| %>
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1615817198611-3a444017a48f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80');">
                  <img class="card-img d-none" src="https://source.unsplash.com/600x900/?computer,design" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
                  <div class="card-img-overlay d-flex flex-column">
                    <div class="card-body">
                      <small class="card-meta mb-2">My Chef</small>
                      <h4 class="card-title mt-0 "><a class="text-white" herf="#">My Chef</a></h4><br>
                      <h6>Name: <%= chef.first_name %> <%= chef.last_name %></h6><br>
                      <h6>Speciality: <%= chef.speciality %></h6><br>
                      <h6>Location: <%= chef.location %></h6><br>
                      <h6>Price: <%= chef.price %>TL</h6>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </section>
  <% end %>
</div>

  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

      <div class="index-header"><h2>My Bookings</h2></div>

 <section class="wrapper"><% @bookings.each do |booking| %>
  <div class="container">

<div class="row">
  <div class="col-sm-4"><div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1615817198611-3a444017a48f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80');">
         <img class="card-img d-none" src="https://source.unsplash.com/600x900/?computer,design" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
         <div class="card-body">
            <small class="card-meta mb-2">My Bookings</small>
            <h4 class="card-title mt-0 "><a class="text-white" herf="#">My Bookings</a></h4><br>
            <h6>Booked Chef: <%= booking.chef.first_name %> <%= booking.chef.last_name %></h6><br>
            <h6>Start Date: <%= booking.start_time %></h6><br>
            <h6>End Date: <%= booking.end_time %></h6><br>
            <h6>Total Amount: <%= booking.total_price %></h6>




          </div>
        </div>
      </div></div>

</div>

</div>
</section>
<% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chef's Kiss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://blog.radissonblu.com/wp-content/uploads/2014/09/Chef-garnishing-a-fine-dining-dish.jpg);">
    <div class="container">
      <h1 class="mx-auto my-0 text-uppercase">CHEF'S KISS</h1>
      <br>
      <h4 class="text-white mx-auto mt-2 mb-5">Find best chefs in your area!</h4>
      <%= link_to 'OUR CHEFS', chefs_path, class: 'btn js-scroll-trigger' %>
    </div>

  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h3 class="text-white mb-4">Built for Your Service</h3>
          <p>Need a chef for your big party? Tired of cooking at home? All you need is Chef's Kiss.</p>
        </div>
      </div>
    </div>
  </section>

<section class="wrapper">
  <div class="container">

<div class="row">
 <div class="col-sm-4"><div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1551218808-94e220e084d2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80');">
         <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
         <div class="card-body">
            <small class="card-meta mb-2">Contact Us</small>
            <h4 class="card-title mt-0 "><a class="text-white" herf="#">Contact Us</a></h4>

          </div>
          <div class="card-footer">
           <div class="media">
            <div class="media-body">
          </div>
</div>
          </div>
        </div>
      </div></div>
     <div class="col-sm-4"><div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80');">
         <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tree,nature" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
         <div class="card-body">
            <small class="card-meta mb-2">About Us</small>
            <h4 class="card-title mt-0 "><a class="text-white" herf="#">About Us</a></h4>
          </div>
          <div class="card-footer">
           <div class="media">
      <div class="media-body">
      </div>
    </div>
          </div>
        </div>
      </div></div>
  <div class="col-sm-4"><div class="card text-white card-has-bg click-col" style="background-image:url('https://images.unsplash.com/photo-1615817198611-3a444017a48f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80');">
         <img class="card-img d-none" src="https://source.unsplash.com/600x900/?computer,design" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
         <div class="card-body">
            <small class="card-meta mb-2">Career</small>
            <h4 class="card-title mt-0 "><a class="text-white" herf="#">Career</a></h4>

          </div>
          <div class="card-footer">
           <div class="media">
  <div class="media-body">


  </div>
</div>
          </div>
        </div>
      </div></div>

</div>

</div>
</section>


  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright © ChefsKiss 2021
    </div>
  </footer>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.dictionary.com/e/wp-content/uploads/2020/01/ChefKiss_800x800-300x300.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Chefs", chefs_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>